[job]
dump_folder = "./outputs"
description = "Instella 3B training"
print_config = false
custom_config_module = "modeloptimizer.config.job_config"

[metrics]
log_freq = 1
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "Instella-3B"
hf_assets_path = "/group/ossmodelzoo/hanwang2/huggingface/hub/models--amd--Instella-3B-Stage1/snapshots/cb33253ab0a5b9f2ea0b98f3edd818d46454580e"
converters = ["modeloptimizer"]

[modeloptimizer]
recipe = "./modeloptimizer/models/llama3/configs/recipe.yaml"

[training]
dtype = "bfloat16"
local_batch_size = 2
global_batch_size = 4
seq_len = 4096
steps = 1
dataset = "wikitext_test"

[debug]
seed = 1234

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
pipeline_parallel_degree = 2
context_parallel_degree = 1

[checkpoint]
enable = true
folder = "checkpoint"
interval = 100
keep_latest_k = 2
last_save_model_only = true
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]
initial_load_path = "/group/ossmodelzoo/hanwang2/huggingface/hub/models--amd--Instella-3B-Stage1/snapshots/cb33253ab0a5b9f2ea0b98f3edd818d46454580e"
initial_load_in_hf = true

[compile]
enable=false
components = ["loss"] # ["model", "loss"]

[activation_checkpoint]
mode = "none"

[validation]
enable = true
dataset = "wikitext_test"
freq = 10
local_batch_size = 2
seq_len = 4096
steps = 10
