[job]
dump_folder = "./outputs"
description = "Llama 3 8B training"
print_config = false
custom_config_module = "modeloptimizer.config.job_config"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "8B"
hf_assets_path = "/wekafs/guanchen/modelzoo/meta-llama/Llama-3.1-8B"
converters = ["modeloptimizer"]

[modeloptimizer]
recipe = "./modeloptimizer/models/llama3/configs/recipe.yaml"

[training]
dtype = "bfloat16"
local_batch_size = 1
global_batch_size = 64
seq_len = 8192
steps = 1
dataset = "wikitext_test"

[debug]
seed = 1234

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = true
folder = "checkpoint"
interval = 10
last_save_model_only = true
export_dtype = "float32"
async_mode = "disabled"
initial_load_path = "/wekafs/guanchen/modelzoo/meta-llama/Llama-3.1-8B"
initial_load_in_hf = true

[compile]
enable=false
components = ["loss"] # ["model", "loss"]

[activation_checkpoint]
mode = "none"

[validation]
enable = true
dataset = "wikitext_test"
freq = 10
local_batch_size = 1
seq_len = 8192
steps = 10
