[job]
dump_folder = "./outputs"
description = "Llama 3 8B training"
print_config = false
custom_config_module = "modeloptimizer.config.job_config"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 1
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "8B"
hf_assets_path = "/group/ossmodelzoo/hanwang2/meta-llama3/Meta-Llama-3-8B-hf"
converters = ["modeloptimizer"]

[quantization.global_config.input]
quantizer = "InputINTQuantizer"
bit = 8
round_mode = "EVEN"
sym_mode = true
narrow_range = false
scale_PoT_round_mode = "CEIL"
use_qoperator = false
granularity = "per-tensor"
group_channel_size = 1
signed_mode = true
scale_type = "fp32"
scale_int_bit = 16
block_size = 128
dynamic_mode = true

[quantization.global_config.weight]
quantizer = "WeightINTQuantizer"
bit = 8
round_mode = "EVEN"
sym_mode = true
narrow_range = false
scale_PoT_round_mode = "CEIL"
use_qoperator = false
granularity = "per-tensor"
group_channel_size = 1
signed_mode = true
scale_type = "fp32"
scale_int_bit = 16
block_size = 128
dynamic_mode = true

[quantization.layer_config.output.input]
quantizer = "origin"

[quantization.layer_config.output.weight]
quantizer = "origin"

[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 2

[training]
local_batch_size = 1
seq_len = 8192
max_norm = 1.0
steps = 10
dataset = "c4_test"

[debug]
seed = 1234

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable = false
folder = "checkpoint"
interval = 150
last_save_model_only = true
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[compile]
enable=false
components = ["loss"] # ["model", "loss"]

[activation_checkpoint]
mode = "none"  # ["none", "selective", "full"]
selective_ac_option = "1"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[validation]
enable = false
dataset = "c4_validation"
freq = 100
local_batch_size = 2
seq_len = 8192
# steps = 1440 # mlperf uses the first 47,185,920 tokens
steps = 100
