# sparsity_stage:
#   sparsity_modifiers:
#     WandaPruningModifier:
#       sparsity: 0.5
#       mask_structure: "2:4"
#       targets: ["Linear"]
#       ignore: ["output"]
quantization_stage:
  quantization_modifiers:
    QuantizationModifier:
      ignore: ["output"]
      config_groups:
        group_0:
          weights:
            num_bits: 8
            type: "int"
            symmetric: true
            strategy: "tensor"
          input_activations:
            num_bits: 8
            type: "int"
            symmetric: true
            strategy: "tensor"
            observer: "minmax"
          targets: ["Linear"]
    SelfDistillationModifier:
      criterion: "LogitsDistillationLoss"
      targets: ["__all__"]
      steps: 10
      warmup_steps: 0
      lr: 1e-4
      min_lr_factor: 1.0
      decay_ratio: null
      decay_type: "linear"
      optimizer: "AdamW"
