base:
  seed: &seed 42

model:
  type: Llama
  path: /group/archive_dataset_6_nobkup/archive_modelzoo/sequence_learning/weights/nlp-pretrained-model/meta-llama/Llama-3.2-1B
  torch_dtype: auto

calib:
  dataset:
    name: wikitext
    subset_name: wikitext-2-raw-v1
    split: train
    download: True
    download_mode: reuse_dataset_if_exists
    cache_dir: /group/ossdphi_algo_scratch_13/guanchen/datasets/calibration/wikitext2
    hf_context_key: text
  processing:
    n_samples: 8
    bs: 1
    seq_len: 512
    preproc: wikitext2_gptq
    seed: *seed

eval_perplexity:
  data_configs:
    - dataset:
        name: allenai/c4
        subset_name: default
        data_files:
            validation: "en/c4-validation.00000-of-00008.json.gz"
        split: validation[:1100]
        download: True
        download_mode: reuse_dataset_if_exists
        cache_dir: /group/ossdphi_algo_scratch_13/guanchen/datasets/calibration/c4
        revision: 607bd4c8450a42878aa9ddc051a65a055450ef87
        hf_context_key: text
      processing:
        bs: 1
        seq_len: 2048
        preproc: wikitext2_test
    - dataset:
        name: wikitext
        subset_name: wikitext-2-raw-v1
        split: test
        download: True
        download_mode: reuse_dataset_if_exists
        cache_dir: /group/ossdphi_algo_scratch_13/guanchen/datasets/calibration/wikitext2
        hf_context_key: text
      processing:
        bs: 1
        seq_len: 2048
        preproc: wikitext2_test

  eval_type: [prefill]
  eval_checkpoints: [pretrained, transformed]
  bs: 1
  seq_len: 2048

eval_downstream:
  eval_checkpoints: [pretrained, transformed]
  task_names: [openbookqa, arc_challenge]
  num_fewshots: [0, 0]
  batch_size: 1

optimization:
  sparse:
    method: Wanda
    weight:
      sparsity: 0.5
    sparsity_out: False

save:
  save_trans: False
  save_path: ./save
