base:
  seed: &seed 42

model:
  type: Llama
  path: /wekafs/guanchen/modelzoo/meta-llama/Llama-3.2-1B
  torch_dtype: auto

eval:
  eval_perplexity:
    data_configs:
      - dataset:
          name: wikitext
          subset_name: wikitext-2-raw-v1
          split: test
          download: True
          download_mode: reuse_dataset_if_exists
          cache_dir: /wekafs/guanchen/datasets/calibration/wikitext2
          hf_context_key: text
        processing:
          bs: 1
          seq_len: 2048
          preproc: test_jointdoc
          preproc_kwargs:
            sep: '\n\n'
    eval_type: [prefill]
  eval_checkpoints: [pretrained, transformed]

optimization:
  quantization:
    method: RTN
    weight:
      quant_dtype: int
      bit: 4
      symmetric: True
      granularity: per_group
      group_size: 32
    act:
      quant_dtype: int
      bit: 4
      symmetric: True
      granularity: per_group
      group_size: 32
        
save:
