training_stage:
  lpt_modifiers:
    LowPrecisionTrainingModifier:
      scheme: "mxfp4"
      targets: ["Linear", "GptOssGroupedExperts"]
      # targets: ["Linear"]
      #ignore: ["lm_head", "re:.*\\.router\\.gate"]
      #ignore: ["lm_head", "re:.*\\.router\\.gate", "re:layers\\.0\\.*", "re:layers\\.22\\.*", "re:layers\\.23\\.*"]
      ignore: ["lm_head", "re:.*\\.router\\.gate", "re:layers\\.\\d+\\.attention\\.*"]
      #ignore: ["lm_head", "re:.*\\.router\\.gate", "re:layers\\.0\\.*", "re:layers\\.22\\.*", "re:layers\\.23\\.*", "re:layers\\.\\d+\\.attention\\.*"]
      use_2dblock_x: false
      use_2dblock_w: true
      use_hadamard: true
      use_sr_grad: true

      # differential gradient estimation, disabled by default
      use_dge: false

      # choices: none, static, dynamic
      clip_mode: none

      # 2-level scaling, disabled by default
      # NVFP4 requires tensorwise scaling or you will get overflow issues
      two_level_scaling: none

      use_uos: true

      # weight de-oscillation, disabled by default
      deosc_step: 768
      deosc_period: 100
      deosc_ratio: 4.0

  lpt_fp8_modifiers:
    LowPrecisionTrainingModifier:
      scheme: "mxfp8_e4m3"
      #targets: ["re:layers\\.0\\.*.*\\.inner_experts", "re:layers\\.22\\.*.*\\.inner_experts", "re:layers\\.23\\.*.*\\.inner_experts", "re:layers\\.\\d+\\.attention\\.*\\.(qkv_linear\\.wqkv|wo)"]
      targets: ["re:layers\\.\\d+\\.attention\\.*\\.(qkv_linear\\.wqkv|wo)"]
      use_2dblock_x: false
      use_2dblock_w: true
      use_hadamard: false
      use_sr_grad: false
