base:
  seed: &seed 42

model:
  type: Llama
  path: /wekafs/guanchen/modelzoo/meta-llama/Llama-3.2-1B
  torch_dtype: auto

calib:
  dataset:
    name: allenai/c4
    subset_name: default
    data_files:
      train: "en/c4-train.00000-of-01024.json.gz"
    split: train
    download: True
    download_mode: reuse_dataset_if_exists
    cache_dir: /wekafs/guanchen/datasets/calibration/c4
    revision: 607bd4c8450a42878aa9ddc051a65a055450ef87
    hf_context_key: text
  processing:
    n_samples: 32
    bs: 1
    seq_len: 4096
    preproc: calib_truncated_long_text_random
    seed: *seed

eval:
  eval_perplexity:
    data_configs:
      - dataset:
          name: wikitext
          subset_name: wikitext-2-raw-v1
          split: test
          download: True
          download_mode: reuse_dataset_if_exists
          cache_dir: /wekafs/guanchen/datasets/calibration/wikitext2
          hf_context_key: text
        processing:
          bs: 1
          seq_len: 2048
          preproc: test_jointdoc
          preproc_kwargs:
            sep: '\n\n'
    eval_type: [prefill]
  eval_checkpoints: [pretrained, transformed]

optimization:
  pruning:
    method: WandaStructured
    weight:
      sparsity: 0.25
      prune_attn: True
      prune_mlp: True
      prune_embedding: False
      prune_layer: False
      prune_sublayer: False

save:
  save_optimization_metadata_path: /wekafs/guanchen/Model-Optimizer/save/wanda-structured/masks
  save_transformed_path: /wekafs/guanchen/Model-Optimizer/save/wanda-structured/hf
  save_optimized_path: /wekafs/guanchen/Model-Optimizer/save/wanda-structured/compressed
